# Contacts Table

## As is

There are two sheets for tier 1 and 2 with the following columns accross both:

- Firm	
- Name	
    - Unique names currently; for scalability should have a unique identifier
    - Do we want to split name into first and last only?
    -  Some names have additional titles
- Title	
    - TODO: move titles in name to title
- Group	
    - Do we want to rename to Vertical?
- Sub-Vertical	
- E-mail	
- Phone	
- Secondary Phone - Is secondary Business cell?	- make asumption
- City
    - Has countries and states
    - Split country, state and city
- Birthday	
- Coverage Person 
    - There are no contacts for them, just a name attach to the bank/ firm contact
- Preferred Contact Method
    - Three choices be primary cell, secondary/business phone, or email?

## To be

Both sheets should be combined with a flag number for tier:

- Contact ID           (PK)(string)
- Firm ID              (FK)(string)
- First Name               (string)
- Last Name                (string)
- Title                    (string)
- Group                    (string)
- Sub-Vertical             (string)
- E-mail                   (string)
- Phone                    (string)
- Secondary Phone          (string)
- Country                  (string)
- State                    (string)
- City                     (string)
- Birthday                 (Date)
- Preferred Contact Method (string)
- Coverage Person          (string)
- Tier                     (Int)

Is a dimentional table - only modified when new contacts are made

In [2]:
import pandas as pd

In [33]:
path = "..\data\Contacts.xlsx"
sheet1 = pd.read_excel(path, sheet_name="Tier 1's")
sheet2 = pd.read_excel(path, sheet_name="Tier 2's")

In [26]:
display(sheet1)

,Firm,Name,Title,Group,Sub-Vertical,E-mail,Phone,Secondary Phone,City,Birthday,Coverage Person,Preferred Contact Method
0,Harris Williams,Robert Baltimore,Managing Director,Business Services,Business Services,BBaltimore@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",2/25/1966,Hannah Jumper,Email
1,Harris Williams,Brian Lucas,Managing Director,Business Services,Business Services,blucas@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",9/3/1953,Kripa Shah,Business Phone
2,Harris Williams,Luke Semple,Managing Director,Business Services,Business Services,lsemple@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",3/27/1962,Emily Royal,Cell Phone
3,Harris Williams,Drew Spitzer,Managing Director,Business Services,Business Services,aspitzer@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",4/28/1964,Russ Barner,Business Phone
4,Harris Williams,Derek Lewis,Managing Director,Business Services,Business Services,dlewis@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",4/24/1971,Daniel Ding,Cell Phone
...,...,...,...,...,...,...,...,...,...,...,...,...
268,Barclays,Aiden Hallett,Director,Technology,Data & Information Services,aiden.hallett@barclays.com,212-526-0929,NaN,"New York, NY",5/30/1975,Hannah Jumper,Email
269,Barclays,Ryan McNamara,Director,Technology,Business Services,ryan.t.mcnamara@barclays.com,312-609-7319,NaN,"Chicago, IL",8/27/1955,Jeannie Blackwood,Cell Phone
270,William Blair,Jon Skinner,Head of Technology Investment Banking,Technology,Technology Services,jskinner@williamblair.com,(312) 364-5408,NaN,"Chicago, IL",3/23/1963,Russ Barner,Cell Phone
271,Credit Suisse,Brian Gudofsky,"Co-Head Technology, Managing Director",Technology,Technology Services,brian.gudofsky@creidt-suisse.com,212-325-6571,NaN,"New York, NY",10/26/1946,Hannah Jumper,Business Phone
272,Credit Suisse,David Goldstein,"Vice Chairman Technology, Managing Director",Technology,Technology Services,david.goldstein@credit-suisse.com,212-325-0907,NaN,"New York, NY",11/20/1942,Jeannie Blackwood,Email

In [27]:
print(sheet1.describe())

                  Firm              Name              Title  \
count              273               273                273
unique              18               273                 74
top     Morgan Stanely  Robert Baltimore  Managing Director
freq                30                 1                140

                    Group       Sub-Vertical                         E-mail  \
count                 273                273                            273
unique                  9                 22                            273
top     Business Services  Business Services  BBaltimore@harriswilliams.com
freq                  118                 47                              1

                 Phone Secondary Phone          City  Birthday  \
count              250               3           273       273
unique             245               3            15       271
top     (804) 648-0072  (917) 304-8472  New York, NY  7/3/1970
freq                 6               1           193         2

       Coverage Person Preferred Contact Method
count              273                      273
unique               6                        3
top      Hannah Jumper               Cell Phone
freq                49                      135

In [35]:
sheet1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Firm                      273 non-null    object
 1   Name                      273 non-null    object
 2   Title                     273 non-null    object
 3   Group                     273 non-null    object
 4   Sub-Vertical              273 non-null    object
 5   E-mail                    273 non-null    object
 6   Phone                     250 non-null    object
 7   Secondary Phone           3 non-null      object
 8   City                      273 non-null    object
 9   Birthday                  273 non-null    object
 10  Coverage Person           273 non-null    object
 11  Preferred Contact Method  273 non-null    object
dtypes: object(12)
memory usage: 25.7+ KB

In [28]:
sheet1['Name'].str.strip()
split_df = pd.concat([sheet1,sheet1['Name'].str.split(' ', expand=True)], axis=1)
display(split_df)
# Inconsitency in names - should not be split by 4

,Firm,Name,Title,Group,Sub-Vertical,E-mail,Phone,Secondary Phone,City,Birthday,Coverage Person,Preferred Contact Method,0,1,2,3,4
0,Harris Williams,Robert Baltimore,Managing Director,Business Services,Business Services,BBaltimore@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",2/25/1966,Hannah Jumper,Email,Robert,Baltimore,None,None,None
1,Harris Williams,Brian Lucas,Managing Director,Business Services,Business Services,blucas@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",9/3/1953,Kripa Shah,Business Phone,Brian,Lucas,None,None,None
2,Harris Williams,Luke Semple,Managing Director,Business Services,Business Services,lsemple@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",3/27/1962,Emily Royal,Cell Phone,Luke,Semple,None,None,None
3,Harris Williams,Drew Spitzer,Managing Director,Business Services,Business Services,aspitzer@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",4/28/1964,Russ Barner,Business Phone,Drew,Spitzer,None,None,None
4,Harris Williams,Derek Lewis,Managing Director,Business Services,Business Services,dlewis@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",4/24/1971,Daniel Ding,Cell Phone,Derek,Lewis,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,Barclays,Aiden Hallett,Director,Technology,Data & Information Services,aiden.hallett@barclays.com,212-526-0929,NaN,"New York, NY",5/30/1975,Hannah Jumper,Email,Aiden,Hallett,None,None,None
269,Barclays,Ryan McNamara,Director,Technology,Business Services,ryan.t.mcnamara@barclays.com,312-609-7319,NaN,"Chicago, IL",8/27/1955,Jeannie Blackwood,Cell Phone,Ryan,McNamara,None,None,None
270,William Blair,Jon Skinner,Head of Technology Investment Banking,Technology,Technology Services,jskinner@williamblair.com,(312) 364-5408,NaN,"Chicago, IL",3/23/1963,Russ Barner,Cell Phone,Jon,Skinner,None,None,None
271,Credit Suisse,Brian Gudofsky,"Co-Head Technology, Managing Director",Technology,Technology Services,brian.gudofsky@creidt-suisse.com,212-325-6571,NaN,"New York, NY",10/26/1946,Hannah Jumper,Business Phone,Brian,Gudofsky,None,None,None
272,Credit Suisse,David Goldstein,"Vice Chairman Technology, Managing Director",Technology,Technology Services,david.goldstein@credit-suisse.com,212-325-0907,NaN,"New York, NY",11/20/1942,Jeannie Blackwood,Email,David,Goldstein,None,None,None

In [29]:
print(split_df[2].unique())
print(split_df[3].unique())
print(split_df[4].unique())

[None '' '(Co-Head)' '(Head']
[None 'of']
[None 'A&D)']

In [30]:
display(sheet2)

,Firm,Name,Title,Group,Sub-Vertical,E-mail,Phone,Secondary Phone,City,Birthday,Coverage Person,Preferred Contact Method
0,Citi,Neeraj Vasudev,Managing Director,Business Services,Transportation & Logistics,neeraj.vasudev@citi.com,212-816-6116,NaN,"New York, NY",12/27/1983,Emily Royal,Cell Phone
1,Citi,Gordon Mackay,Director,Business Services,Industrial & Environmental Services,gordon.mackay@citi.com,212-816-4608,NaN,"New York, NY",5/27/1962,Kripa Shah,Business Phone
2,Citi,Chad Hoeft,Managing Director,Business Services,Facilities Services,chad.hoeft@citi.com,212-816-4977,NaN,"New York, NY",10/19/1947,Hannah Jumper,Cell Phone
3,Citi,Eric Burns,Director,Business Services,Facilities Services,Eric.burns@citi.com,212-816-1970,NaN,"New York, NY",12/23/1973,Jeannie Blackwood,Business Phone
4,Citi,Matthew Musa,Managing Director,Business Services,Facilities Services,matt.musa@citi.com,312-876-6953,NaN,"Chicago, IL",4/13/1983,Kripa Shah,Cell Phone
5,Citi,Brian Fischbein,Managing Director,Business Services,Data & Information Services,brian.fischbein@citi.com,212-816-5940,NaN,"New York, NY",10/16/1944,Emily Royal,Cell Phone
6,Citi,Eish Dhillon,Managing Director,Business Services,IT Services,Eish.Dhillon@citi.com,212-816-3150,NaN,"New York, NY",3/17/1944,Emily Royal,Cell Phone
7,Citi,Stephen Edelman,Managing Director,Business Services,Industrial & Environmental Services,Stephen.Edelman@citi.com,212-816-2868,NaN,"New York, NY",1/25/1953,Russ Barner,Cell Phone
8,Nomura,Mike Rintoul,"Managing Director, Head of Business Services",Business Services,Business Services,michael.rintoul@nomura.com,(212) 436-8178,(917) 846-6951,"New York, NY",1/21/1951,Russ Barner,Email
9,Nomura,David Buscaglia,Director,Business Services,Professional Services,david.buscaglia@nomura.com,(212) 298-4031,(917) 406-3540,"New York, NY",1/21/1948,Jeannie Blackwood,Cell Phone
10,Stifel,Chanan Glambosky,Managing Director,Business Services,Professional Services,glamboskyc@stifel.com,(212) 847-6443,(202) 236-2318,"New York, NY",1/1/1960,Hannah Jumper,Business Phone
11,FT Partners,Steve McLaughlin,Managing Partner,Financial Services,Financial Technology,steve.mclaughlin@ftpartners.com,(415) 512-8704,NaN,"San Francisco, CA",2/8/1976,Emily Royal,Cell Phone
12,FT Partners,Melissa Wasser,"Director, Head of Capital Markets",Financial Services,Product Group,Melissa.Wasser@ftpartners.com,(609) 304-5625,NaN,"New York, NY",4/24/1971,Russ Barner,Cell Phone
13,FT Partners,David Lemelman,Vice President,Financial Services,Financial Technology,David.Lemelman@ftpartners.com,(212) 225-8474,NaN,"New York, NY",5/27/1958,Daniel Ding,Cell Phone
14,FT Partners,Nick Seibert,Director,Financial Services,Financial Technology,Nick.Seibert@ftpartners.com,(212) 558-9316,NaN,"New York, NY",1/26/1957,Daniel Ding,Cell Phone
15,FT Partners,Stephen Stout,Managing Director,Financial Services,Financial Technology,stephen.stout@ftpartners.com,NaN,NaN,"New York, NY",8/20/1975,Emily Royal,Business Phone
16,FT Partners,Paul VanderMarck,Managing Director,Financial Services,Financial Technology,paul.vandermarck@ftpartners.com,NaN,NaN,"New York, NY",6/20/1951,Kripa Shah,Email
17,Citi,Peter Babej,"Managing Director, Head – Global FIG",Financial Services,Asset Management,peter.babej@citi.com,212-816-5900,NaN,"New York, NY",10/27/1964,Russ Barner,Email
18,Citi,David Head,"Managing Director, Chairman – Global FIG",Financial Services,Asset Management,david.head@citi.com,212-816-9881,NaN,"New York, NY",12/28/1954,Daniel Ding,Email
19,Citi,Christian Anderson,"Managing Director, Co-Head – Global GAM",Financial Services,Asset Management,christian.anderson@citi.com,212-816-9840,NaN,"New York, NY",8/28/1957,Daniel Ding,Email
20,Citi,Brad Coleman,"Managing Director, Chairman – Global GAM",Financial Services,Asset Management,brad.coleman@citi.com,212-816-9215,NaN,"New York, NY",7/16/1948,Emily Royal,Email
21,Citi,Thomas Heath,"Managing Director, Co-Head of Banks and Divers...",Financial Services,Banks / Lending,Thomas.Heath@citi.com,212-816-8484,NaN,"New York, NY",1/22/1972,Kripa Shah,Cell Phone
22,Citi,Robert Goldstein,Managing Director,Financial Services,Banks / Lending,Robert.Goldstein@citi.com,212-816-3776,NaN,"New York, NY",11/13/1968,Russ Barner,Business Phone
23,Citi,Ian Wesson,Managing Director,Financial Services,Banks / Lending,Ian.Wesson@citi.com,212-816-1282,NaN,"New York, NY",4/12/1970,Hannah Jumper,Cell Phone
24,Citi,Seth Heaton,Managing Director,Financial Services,Banks / Lending,Seth.Heaton@citi.com,212-816-8226,NaN,"New York, NY",9/25/1967,Hannah Jumper,Cell Phone
25,Citi,Matt Beitzel,Managing Director,Financial Services,Banks / Lending,Matt.Beitzel@citi.com,312-876-8808,NaN,"New York, NY",12/3/1963,Jeannie Blackwood,Cell Phone
26,Citi,Peter Bickford,"Co-Head of Insurance, Managing Director",Financial Services,Insurance,Peter.Bickford@citi.com,212-816-4022,NaN,"New York, NY",4/2/1976,Jeannie Blackwood,Cell Phone
27,Citi,Gautam Chawla,"Co-Head of Insurance, Managing Director",Financial Services,Insurance,Gautam.Chawla@citi.com,212-816-9806,NaN,"New York, NY",9/4/1965,Russ Barner,Business Phone
28,Citi,Clifford Brokaw,Managing Director,Financial Services,Insurance,Clifford.Brokaw@citi.com,212-816-6767,NaN,"New York, NY",12/21/1979,Emily Royal,Email
29,Citi,Raymond Peters,Managing Director,Financial Services,Insurance,Raymond.Peters@citi.com,212-816-6100,NaN,"New York, NY",1/5/1963,Kripa Shah,Cell Phone
30,Citi,Rick Diamond,"Managing Director, Global Head of Financial Te...",Financial Services,Financial Technology,Rick.Diamond@citi.com,212-816-2777,NaN,"New York, NY",7/19/1970,Hannah Jumper,Business Phone
31,Citi,Mathieu Salas,"Managing Director, Head of Global Financial Te...",Financial Services,Financial Technology,Mathieu.Salas@citi.com,212-816-5502,NaN,"New York, NY",10/21/1983,Jeannie Blackwood,Cell Phone
32,Citi,Dane Graham,Managing Director,Financial Services,Asset Management,Dane.Graham@citi.com,212-816-8219,NaN,"New York, NY",10/18/1969,Kripa Shah,Business Phone
33,Cowen,Kevin Manning,"Managing Director, Head of Diversified Industr...",Industrials,Industrial & Environmental Services,kevin.manning@cowen.com,(312) 577-2228,(773) 304-6721,"Chicago, IL",9/10/1980,Emily Royal,Cell Phone
34,Petsky Prunier,Sanjay Chadda,Managing Director & Partner,Marketing Services,Marketing Services,schadda@petskyprunier.com,212-842-6022,NaN,"New York, NY",9/5/1980,Kripa Shah,Email
35,Petsky Prunier,Marc Flor,Director,Marketing Services,Marketing Services,mflor@petskyprunier.com,212-842-6034,NaN,"New York, NY",4/15/1950,Hannah Jumper,Email
36,AdMedia,Oliver Schweitzer,Managing Director,Marketing Services,Marketing Services,oschweitzer@admediapartners.com,(212) 759-1870,NaN,"New York, NY",4/1/1978,Jeannie Blackwood,Cell Phone
37,AdMedia,Greg Smith,Managing Director,Marketing Services,Marketing Services,gsmith@admediapartners.com,NaN,NaN,"New York, NY",5/3/1968,Kripa Shah,Business Phone

In [31]:
print(sheet2.describe())

        Firm            Name              Title               Group  \
count     38              38                 38                  38
unique     7              38                 16                   4
top     Citi  Neeraj Vasudev  Managing Director  Financial Services
freq      24               1                 18                  22

                Sub-Vertical                   E-mail         Phone  \
count                     38                       38            35
unique                    13                       38            35
top     Financial Technology  neeraj.vasudev@citi.com  212-816-6116
freq                       7                        1             1

       Secondary Phone          City    Birthday Coverage Person  \
count                4            38          38              38
unique               4             3          38               6
top     (917) 846-6951  New York, NY  12/27/1983     Emily Royal
freq                 1            35           1               8

       Preferred Contact Method
count                        38
unique                        3
top                  Cell Phone
freq                         20

In [32]:
sheet2['Name'].str.strip()
split_df = pd.concat([sheet2,sheet2['Name'].str.split(' ', expand=True)], axis=1)
display(split_df)

,Firm,Name,Title,Group,Sub-Vertical,E-mail,Phone,Secondary Phone,City,Birthday,Coverage Person,Preferred Contact Method,0,1,2
0,Citi,Neeraj Vasudev,Managing Director,Business Services,Transportation & Logistics,neeraj.vasudev@citi.com,212-816-6116,NaN,"New York, NY",12/27/1983,Emily Royal,Cell Phone,Neeraj,Vasudev,None
1,Citi,Gordon Mackay,Director,Business Services,Industrial & Environmental Services,gordon.mackay@citi.com,212-816-4608,NaN,"New York, NY",5/27/1962,Kripa Shah,Business Phone,Gordon,Mackay,None
2,Citi,Chad Hoeft,Managing Director,Business Services,Facilities Services,chad.hoeft@citi.com,212-816-4977,NaN,"New York, NY",10/19/1947,Hannah Jumper,Cell Phone,Chad,Hoeft,None
3,Citi,Eric Burns,Director,Business Services,Facilities Services,Eric.burns@citi.com,212-816-1970,NaN,"New York, NY",12/23/1973,Jeannie Blackwood,Business Phone,Eric,Burns,None
4,Citi,Matthew Musa,Managing Director,Business Services,Facilities Services,matt.musa@citi.com,312-876-6953,NaN,"Chicago, IL",4/13/1983,Kripa Shah,Cell Phone,Matthew,Musa,None
5,Citi,Brian Fischbein,Managing Director,Business Services,Data & Information Services,brian.fischbein@citi.com,212-816-5940,NaN,"New York, NY",10/16/1944,Emily Royal,Cell Phone,Brian,Fischbein,None
6,Citi,Eish Dhillon,Managing Director,Business Services,IT Services,Eish.Dhillon@citi.com,212-816-3150,NaN,"New York, NY",3/17/1944,Emily Royal,Cell Phone,Eish,Dhillon,None
7,Citi,Stephen Edelman,Managing Director,Business Services,Industrial & Environmental Services,Stephen.Edelman@citi.com,212-816-2868,NaN,"New York, NY",1/25/1953,Russ Barner,Cell Phone,Stephen,Edelman,None
8,Nomura,Mike Rintoul,"Managing Director, Head of Business Services",Business Services,Business Services,michael.rintoul@nomura.com,(212) 436-8178,(917) 846-6951,"New York, NY",1/21/1951,Russ Barner,Email,Mike,Rintoul,None
9,Nomura,David Buscaglia,Director,Business Services,Professional Services,david.buscaglia@nomura.com,(212) 298-4031,(917) 406-3540,"New York, NY",1/21/1948,Jeannie Blackwood,Cell Phone,David,Buscaglia,None
10,Stifel,Chanan Glambosky,Managing Director,Business Services,Professional Services,glamboskyc@stifel.com,(212) 847-6443,(202) 236-2318,"New York, NY",1/1/1960,Hannah Jumper,Business Phone,Chanan,Glambosky,None
11,FT Partners,Steve McLaughlin,Managing Partner,Financial Services,Financial Technology,steve.mclaughlin@ftpartners.com,(415) 512-8704,NaN,"San Francisco, CA",2/8/1976,Emily Royal,Cell Phone,Steve,McLaughlin,None
12,FT Partners,Melissa Wasser,"Director, Head of Capital Markets",Financial Services,Product Group,Melissa.Wasser@ftpartners.com,(609) 304-5625,NaN,"New York, NY",4/24/1971,Russ Barner,Cell Phone,Melissa,Wasser,None
13,FT Partners,David Lemelman,Vice President,Financial Services,Financial Technology,David.Lemelman@ftpartners.com,(212) 225-8474,NaN,"New York, NY",5/27/1958,Daniel Ding,Cell Phone,David,Lemelman,None
14,FT Partners,Nick Seibert,Director,Financial Services,Financial Technology,Nick.Seibert@ftpartners.com,(212) 558-9316,NaN,"New York, NY",1/26/1957,Daniel Ding,Cell Phone,Nick,Seibert,None
15,FT Partners,Stephen Stout,Managing Director,Financial Services,Financial Technology,stephen.stout@ftpartners.com,NaN,NaN,"New York, NY",8/20/1975,Emily Royal,Business Phone,Stephen,Stout,None
16,FT Partners,Paul VanderMarck,Managing Director,Financial Services,Financial Technology,paul.vandermarck@ftpartners.com,NaN,NaN,"New York, NY",6/20/1951,Kripa Shah,Email,Paul,VanderMarck,None
17,Citi,Peter Babej,"Managing Director, Head – Global FIG",Financial Services,Asset Management,peter.babej@citi.com,212-816-5900,NaN,"New York, NY",10/27/1964,Russ Barner,Email,Peter,Babej,None
18,Citi,David Head,"Managing Director, Chairman – Global FIG",Financial Services,Asset Management,david.head@citi.com,212-816-9881,NaN,"New York, NY",12/28/1954,Daniel Ding,Email,David,Head,None
19,Citi,Christian Anderson,"Managing Director, Co-Head – Global GAM",Financial Services,Asset Management,christian.anderson@citi.com,212-816-9840,NaN,"New York, NY",8/28/1957,Daniel Ding,Email,Christian,Anderson,None
20,Citi,Brad Coleman,"Managing Director, Chairman – Global GAM",Financial Services,Asset Management,brad.coleman@citi.com,212-816-9215,NaN,"New York, NY",7/16/1948,Emily Royal,Email,Brad,Coleman,None
21,Citi,Thomas Heath,"Managing Director, Co-Head of Banks and Divers...",Financial Services,Banks / Lending,Thomas.Heath@citi.com,212-816-8484,NaN,"New York, NY",1/22/1972,Kripa Shah,Cell Phone,Thomas,Heath,None
22,Citi,Robert Goldstein,Managing Director,Financial Services,Banks / Lending,Robert.Goldstein@citi.com,212-816-3776,NaN,"New York, NY",11/13/1968,Russ Barner,Business Phone,Robert,Goldstein,
23,Citi,Ian Wesson,Managing Director,Financial Services,Banks / Lending,Ian.Wesson@citi.com,212-816-1282,NaN,"New York, NY",4/12/1970,Hannah Jumper,Cell Phone,Ian,Wesson,None
24,Citi,Seth Heaton,Managing Director,Financial Services,Banks / Lending,Seth.Heaton@citi.com,212-816-8226,NaN,"New York, NY",9/25/1967,Hannah Jumper,Cell Phone,Seth,Heaton,None
25,Citi,Matt Beitzel,Managing Director,Financial Services,Banks / Lending,Matt.Beitzel@citi.com,312-876-8808,NaN,"New York, NY",12/3/1963,Jeannie Blackwood,Cell Phone,Matt,Beitzel,None
26,Citi,Peter Bickford,"Co-Head of Insurance, Managing Director",Financial Services,Insurance,Peter.Bickford@citi.com,212-816-4022,NaN,"New York, NY",4/2/1976,Jeannie Blackwood,Cell Phone,Peter,Bickford,None
27,Citi,Gautam Chawla,"Co-Head of Insurance, Managing Director",Financial Services,Insurance,Gautam.Chawla@citi.com,212-816-9806,NaN,"New York, NY",9/4/1965,Russ Barner,Business Phone,Gautam,Chawla,None
28,Citi,Clifford Brokaw,Managing Director,Financial Services,Insurance,Clifford.Brokaw@citi.com,212-816-6767,NaN,"New York, NY",12/21/1979,Emily Royal,Email,Clifford,Brokaw,None
29,Citi,Raymond Peters,Managing Director,Financial Services,Insurance,Raymond.Peters@citi.com,212-816-6100,NaN,"New York, NY",1/5/1963,Kripa Shah,Cell Phone,Raymond,Peters,None
30,Citi,Rick Diamond,"Managing Director, Global Head of Financial Te...",Financial Services,Financial Technology,Rick.Diamond@citi.com,212-816-2777,NaN,"New York, NY",7/19/1970,Hannah Jumper,Business Phone,Rick,Diamond,None
31,Citi,Mathieu Salas,"Managing Director, Head of Global Financial Te...",Financial Services,Financial Technology,Mathieu.Salas@citi.com,212-816-5502,NaN,"New York, NY",10/21/1983,Jeannie Blackwood,Cell Phone,Mathieu,Salas,None
32,Citi,Dane Graham,Managing Director,Financial Services,Asset Management,Dane.Graham@citi.com,212-816-8219,NaN,"New York, NY",10/18/1969,Kripa Shah,Business Phone,Dane,Graham,None
33,Cowen,Kevin Manning,"Managing Director, Head of Diversified Industr...",Industrials,Industrial & Environmental Services,kevin.manning@cowen.com,(312) 577-2228,(773) 304-6721,"Chicago, IL",9/10/1980,Emily Royal,Cell Phone,Kevin,Manning,None
34,Petsky Prunier,Sanjay Chadda,Managing Director & Partner,Marketing Services,Marketing Services,schadda@petskyprunier.com,212-842-6022,NaN,"New York, NY",9/5/1980,Kripa Shah,Email,Sanjay,Chadda,None
35,Petsky Prunier,Marc Flor,Director,Marketing Services,Marketing Services,mflor@petskyprunier.com,212-842-6034,NaN,"New York, NY",4/15/1950,Hannah Jumper,Email,Marc,Flor,None
36,AdMedia,Oliver Schweitzer,Managing Director,Marketing Services,Marketing Services,oschweitzer@admediapartners.com,(212) 759-1870,NaN,"New York, NY",4/1/1978,Jeannie Blackwood,Cell Phone,Oliver,Schweitzer,None
37,AdMedia,Greg Smith,Managing Director,Marketing Services,Marketing Services,gsmith@admediapartners.com,NaN,NaN,"New York, NY",5/3/1968,Kripa Shah,Business Phone,Greg,Smith,None

In [34]:
combined_contacts = pd.concat([sheet1, sheet2])
display(combined_contacts)

,Firm,Name,Title,Group,Sub-Vertical,E-mail,Phone,Secondary Phone,City,Birthday,Coverage Person,Preferred Contact Method
0,Harris Williams,Robert Baltimore,Managing Director,Business Services,Business Services,BBaltimore@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",2/25/1966,Hannah Jumper,Email
1,Harris Williams,Brian Lucas,Managing Director,Business Services,Business Services,blucas@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",9/3/1953,Kripa Shah,Business Phone
2,Harris Williams,Luke Semple,Managing Director,Business Services,Business Services,lsemple@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",3/27/1962,Emily Royal,Cell Phone
3,Harris Williams,Drew Spitzer,Managing Director,Business Services,Business Services,aspitzer@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",4/28/1964,Russ Barner,Business Phone
4,Harris Williams,Derek Lewis,Managing Director,Business Services,Business Services,dlewis@harriswilliams.com,(804) 648-0072,NaN,"Richmond, VA",4/24/1971,Daniel Ding,Cell Phone
...,...,...,...,...,...,...,...,...,...,...,...,...
33,Cowen,Kevin Manning,"Managing Director, Head of Diversified Industr...",Industrials,Industrial & Environmental Services,kevin.manning@cowen.com,(312) 577-2228,(773) 304-6721,"Chicago, IL",9/10/1980,Emily Royal,Cell Phone
34,Petsky Prunier,Sanjay Chadda,Managing Director & Partner,Marketing Services,Marketing Services,schadda@petskyprunier.com,212-842-6022,NaN,"New York, NY",9/5/1980,Kripa Shah,Email
35,Petsky Prunier,Marc Flor,Director,Marketing Services,Marketing Services,mflor@petskyprunier.com,212-842-6034,NaN,"New York, NY",4/15/1950,Hannah Jumper,Email
36,AdMedia,Oliver Schweitzer,Managing Director,Marketing Services,Marketing Services,oschweitzer@admediapartners.com,(212) 759-1870,NaN,"New York, NY",4/1/1978,Jeannie Blackwood,Cell Phone
37,AdMedia,Greg Smith,Managing Director,Marketing Services,Marketing Services,gsmith@admediapartners.com,NaN,NaN,"New York, NY",5/3/1968,Kripa Shah,Business Phone