# Private Equite Relations Table

## As is

There are one sheets for PE Firms:

- Priority	
    - Do we need this column? All are null
- Company Name	
- Website 
- "AUM (Bns)"	
- Sectors	
- Sample Portfolio Companies
- Contact Name 1	
- Contact 2	
- Comments



## To be

Company info should be in a firm dim table. The columns to be moved:

- Company Name
- Website
- AUM 
    - Will need to remove \n 
- Sectors
    - Will need to delimiate better
- Sample Portfolio Companies
    - Will need to parse better
-

In [50]:
import pandas as pd

In [51]:
path = "..\data\PE Comps.xlsx"
pe_firms = pd.read_excel(path, skiprows=2) # Headers at 2 data at 4 (not date enineering stats) 
pe_firms.drop(index=pe_firms.index[0], axis=0, inplace=True) # Droping extra row - is this a standard?

In [56]:
display(pe_firms)

,Priority,Company Name,Website,AUM\n(Bns),Sectors,Sample Portfolio Companies,Contact Name 1,Contact 2,Comments
1,NaN,AEA Investors LP,www.aeainvestors.com,10.0,- Consumer products\n- Industrial,- Traeger (Current)\n- Barnet (Cosmetic),"Martin Eltrich, III, Partner",NaN,NaN
2,NaN,Audax Private Equity,www.audaxprivateequity.com,11.5,- Industrial,- Chem Specialty Chemicals,"Christopher Satti, Business Dev\n(857) 294-6640",NaN,- We have experience with specialty chemicals ...
3,NaN,CCMP Capital,www.ccmpcapital.com,12.0,- Consumer products\n- Industrial,- Jetro Cash & Carry\n- Shoes for Crews,Richard Zannino,Will Jaudes \nPrincipal,- Are big on Consumer and industrial
4,NaN,Clayton Dubilier & Rice,www.cdr-inc.com,18.0,- Consumer products\n- Industrial,- Roofing Supply Group\n- US Foods\n- HD Supply,NaN,NaN,NaN
5,NaN,Crestview Partners,www.crestview.com,20.0,- Industrial Products,- Key Safety Systems\n- Accuride corporation,"Alex Rose, Partner",NaN,- Have industrial products focus
6,NaN,Genstar Capital,www.gencap.com,8.5,- Industrial Products,- Pretium Packaging\n- Fort Dearborn Company,"Tony Salewski, Managing Director\n415 834 2350",NaN,NaN
7,NaN,Golden Gate Capital,www.goldengatecap.com,14.0,- Consumer products\n- Industrial,- Eddie Bauer\n- Pacsun,Dave Thomas \nManaging Director\n415 983 2700,Scott Middleman \nAssociate\n415 983 2700\nsmi...,Mr. Thomas focuses on investments in Industria...
8,NaN,Gores Group,www.gores.com,2.4,- Consumer products\n- Industrial,- Sage Automotive (previously),NaN,NaN,- One of their strategies on some of their cas...
9,NaN,Harvest Partners,www.harvestpartners.com,2.0,- Industrial Products,- Associated Materials (Prior)\n- Driven Brand...,"Ira D. Kleinman, Senior Managing Director",Paige Daly \nManaging Director\n212 599 6300 e...,- Did addons for Associated Materials while th...
10,NaN,Irving Place Capital,www.irvingplacecapital.com,4.4,- Consumer products\n- Industrial,- Bendon\n- New York and Co\n- Rag and Bone,"David Knoch, Strategic Services and Partners","Devraj Roy \nPartner, Industrials\n212 551 466...",- Have both branded consumer companies and ind...
11,NaN,Kelso & Company,www.kelso.com,11.2,- Consumer Products\n- Building products,- Augusta Sportsware\n- Eagle Foods,Alexander Lynn \nManaging Director\n212 751 39...,Keith Castaldi \nVice President\n212 751 3939\...,- DR says he knows Phil Berney or has heard of...
12,NaN,Kohlberg and Company,www.kohlberg.com,7.5,- Industrial\n- Consumer Products,- Nelson (Neutraceutical)\n- NBG Home Décor Pr...,NaN,NaN,NaN
13,NaN,KPS Capital Partners LP,www.kpsfund.com,5.2,- Consumer products\n- Industrial,- Taylor Made\n- Winoa,NaN,NaN,NaN
14,NaN,Nautic Partners LLC,www.nautic.com,13.0,- Industrial Products,- Custom Windows\n- Precision Engineered Products,Bernard V. Buonanno\nbbuonanno@nautic.com\n(40...,NaN,- We've had contact with them before for FS so...
15,NaN,Palladium Equity Partners,www.palladiumequity.com,2.1,- Consumer products\n- Industrial,- Sahale Snacks\n- Kars Snacks,NaN,NaN,NaN
16,NaN,Platinum Equity,www.platinumequity.com,6.5,- Industrial Products,- SCM Metal Products\n- International textile ...,"David Boutry, Principal Bus Dev\n+1 212.905.0010",NaN,NaN
17,NaN,The Riverside Company,www.riversidecompany.com,6.0,- Consumer Brands\n- Specialty Mfg and Distrib...,- Lille Baby\n- Blue Electronics,Jeremy Holland \nPrincipal of Origination Cons...,NaN,"- Have a full section of ""seeking addons for ...."
18,NaN,Sun Capital Partners,www.suncappart.com,9.0,- Consumer Brands\n- Industrials,- Trulite\n- Arrow Tru-Line,Johnathon Borell \nManaging Director\n212 588 ...,NaN,- DR knows Marc Leder ( I think)\n- They are b...
19,NaN,Thomas H. Lee Partners,www.thl.com,10.0,- Consumer & Retail,- Give & Go Bakery\n- CTI Foods,"Douglas A. Haber, Managing Director\n617-227-1050",NaN,- Big in consumer and retail industry\n- Have ...
20,NaN,TSG Cosumer Partners,www.tsgconsumer.com,5.0,- Consumer Brands,- Smashbox\n- Beauty Bands\n- Elf\n- Cutex,"Michael Layman, Managing Director\n415.217.231...",NaN,- they are purely consumer focussed\n- Seems t...

In [64]:
pe_firms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 1 to 20
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Priority                    0 non-null      float64
 1   Company Name                20 non-null     object
 2   Website                     20 non-null     object
 3   AUM
(Bns)                   20 non-null     float64
 4   Sectors                     20 non-null     object
 5   Sample Portfolio Companies  20 non-null     object
 6   Contact Name 1              15 non-null     object
 7   Contact 2                   5 non-null      object
 8   Comments                    13 non-null     object
dtypes: float64(2), object(7)
memory usage: 1.5+ KB

In [58]:
for row in pe_firms.iterrows():
    print(row)

(1, Priority                                                           NaN
Company Name                                          AEA Investors LP
Website                                           www.aeainvestors.com
AUM\n(Bns)                                                        10.0
Sectors                              - Consumer products\n- Industrial
Sample Portfolio Companies    - Traeger (Current)\n- Barnet (Cosmetic)
Contact Name 1                            Martin Eltrich, III, Partner
Contact 2                                                          NaN
Comments                                                           NaN
Name: 1, dtype: object)
(2, Priority                                                                    NaN
Company Name                                               Audax Private Equity
Website                                              www.audaxprivateequity.com
AUM\n(Bns)                                                                 11.5
Sectors                                                            - Industrial
Sample Portfolio Companies                           - Chem Specialty Chemicals
Contact Name 1                  Christopher Satti, Business Dev\n(857) 294-6640
Contact 2                                                                   NaN
Comments                      - We have experience with specialty chemicals ...
Name: 2, dtype: object)
(3, Priority                                                          NaN
Company Name                                             CCMP Capital
Website                                           www.ccmpcapital.com
AUM\n(Bns)                                                       12.0
Sectors                             - Consumer products\n- Industrial
Sample Portfolio Companies    - Jetro Cash & Carry\n- Shoes for Crews
Contact Name 1                                        Richard Zannino
Contact 2                                   Will Jaudes \nPrincipal
Comments                         - Are big on Consumer and industrial
Name: 3, dtype: object)
(4, Priority                                                                  NaN
Company Name                                          Clayton Dubilier & Rice
Website                                                       www.cdr-inc.com
AUM\n(Bns)                                                               18.0
Sectors                                     - Consumer products\n- Industrial
Sample Portfolio Companies    - Roofing Supply Group\n- US Foods\n- HD Supply
Contact Name 1                                                            NaN
Contact 2                                                                 NaN
Comments                                                                  NaN
Name: 4, dtype: object)
(5, Priority                                                               NaN
Company Name                                            Crestview Partners
Website                                                  www.crestview.com
AUM\n(Bns)                                                            20.0
Sectors                                              - Industrial Products
Sample Portfolio Companies    - Key Safety Systems\n- Accuride corporation
Contact Name 1                                          Alex Rose, Partner
Contact 2                                                              NaN
Comments                                  - Have industrial products focus
Name: 5, dtype: object)
(6, Priority                                                                 NaN
Company Name                                                 Genstar Capital
Website                                                       www.gencap.com
AUM\n(Bns)                                                               8.5
Sectors                                                - Industrial Products
Sample Portfolio Companies      - Pretium Packaging\n- Fort Dearborn Company
Contact Name 1                Tony Salewski, Managing Director\n415 834 2350
Contact 2                                                                NaN
Comments                                                                 NaN
Name: 6, dtype: object)
(7, Priority                                                                    NaN
Company Name                                                Golden Gate Capital
Website                                                   www.goldengatecap.com
AUM\n(Bns)                                                                 14.0
Sectors                                       - Consumer products\n- Industrial
Sample Portfolio Companies                              - Eddie Bauer\n- Pacsun
Contact Name 1                   Dave Thomas \nManaging Director\n415 983 2700
Contact 2                     Scott Middleman \nAssociate\n415 983 2700\nsmi...
Comments                      Mr. Thomas focuses on investments in Industria...
Name: 7, dtype: object)
(8, Priority                                                                    NaN
Company Name                                                        Gores Group
Website                                                           www.gores.com
AUM\n(Bns)                                                                  2.4
Sectors                                       - Consumer products\n- Industrial
Sample Portfolio Companies                       - Sage Automotive (previously)
Contact Name 1                                                              NaN
Contact 2                                                                   NaN
Comments                      - One of their strategies on some of their cas...
Name: 8, dtype: object)
(9, Priority                                                                    NaN
Company Name                                                   Harvest Partners
Website                                                 www.harvestpartners.com
AUM\n(Bns)                                                                  2.0
Sectors                                                   - Industrial Products
Sample Portfolio Companies    - Associated Materials (Prior)\n- Driven Brand...
Contact Name 1                        Ira D. Kleinman, Senior Managing Director
Contact 2                     Paige Daly \nManaging Director\n212 599 6300 e...
Comments                      - Did addons for Associated Materials while th...
Name: 9, dtype: object)
(10, Priority                                                                    NaN
Company Name                                               Irving Place Capital
Website                                              www.irvingplacecapital.com
AUM\n(Bns)                                                                  4.4
Sectors                                       - Consumer products\n- Industrial
Sample Portfolio Companies          - Bendon\n- New York and Co\n- Rag and Bone
Contact Name 1                     David Knoch, Strategic Services and Partners
Contact 2                     Devraj Roy \nPartner, Industrials\n212 551 466...
Comments                      - Have both branded consumer companies and ind...
Name: 10, dtype: object)
(11, Priority                                                                    NaN
Company Name                                                    Kelso & Company
Website                                                           www.kelso.com
AUM\n(Bns)                                                                 11.2
Sectors                                - Consumer Products\n- Building products
Sample Portfolio Companies                  - Augusta Sportsware\n- Eagle Foods
Contact Name 1                Alexander Lynn \nManaging Director\n212 751 39...
Contact 2                     Keith Castaldi \nVice President\n212 751 3939\...
Comments                      - DR says he knows Phil Berney or has heard of...
Name: 11, dtype: object)
(12, Priority                                                                    NaN
Company Name                                               Kohlberg and Company
Website                                                        www.kohlberg.com
AUM\n(Bns)                                                                  7.5
Sectors                                       - Industrial\n- Consumer Products
Sample Portfolio Companies    - Nelson (Neutraceutical)\n- NBG Home Décor Pr...
Contact Name 1                                                              NaN
Contact 2                                                                   NaN
Comments                                                                    NaN
Name: 12, dtype: object)
(13, Priority                                                    NaN
Company Name                            KPS Capital Partners LP
Website                                         www.kpsfund.com
AUM\n(Bns)                                                  5.2
Sectors                       - Consumer products\n- Industrial
Sample Portfolio Companies               - Taylor Made\n- Winoa
Contact Name 1                                              NaN
Contact 2                                                   NaN
Comments                                                    NaN
Name: 13, dtype: object)
(14, Priority                                                                    NaN
Company Name                                                Nautic Partners LLC
Website                                                          www.nautic.com
AUM\n(Bns)                                                                 13.0
Sectors                                                   - Industrial Products
Sample Portfolio Companies    - Custom Windows\n- Precision Engineered Products
Contact Name 1                Bernard V. Buonanno\nbbuonanno@nautic.com\n(40...
Contact 2                                                                   NaN
Comments                      - We've had contact with them before for FS so...
Name: 14, dtype: object)
(15, Priority                                                    NaN
Company Name                          Palladium Equity Partners
Website                                 www.palladiumequity.com
AUM\n(Bns)                                                  2.1
Sectors                       - Consumer products\n- Industrial
Sample Portfolio Companies       - Sahale Snacks\n- Kars Snacks
Contact Name 1                                              NaN
Contact 2                                                   NaN
Comments                                                    NaN
Name: 15, dtype: object)
(16, Priority                                                                    NaN
Company Name                                                    Platinum Equity
Website                                                  www.platinumequity.com
AUM\n(Bns)                                                                  6.5
Sectors                                                   - Industrial Products
Sample Portfolio Companies    - SCM Metal Products\n- International textile ...
Contact Name 1                 David Boutry, Principal Bus Dev\n+1 212.905.0010
Contact 2                                                                   NaN
Comments                                                                    NaN
Name: 16, dtype: object)
(17, Priority                                                                    NaN
Company Name                                              The Riverside Company
Website                                                www.riversidecompany.com
AUM\n(Bns)                                                                  6.0
Sectors                       - Consumer Brands\n- Specialty Mfg and Distrib...
Sample Portfolio Companies                     - Lille Baby\n- Blue Electronics
Contact Name 1                Jeremy Holland \nPrincipal of Origination Cons...
Contact 2                                                                   NaN
Comments                      - Have a full section of "seeking addons for ....
Name: 17, dtype: object)
(18, Priority                                                                    NaN
Company Name                                               Sun Capital Partners
Website                                                      www.suncappart.com
AUM\n(Bns)                                                                  9.0
Sectors                                        - Consumer Brands\n- Industrials
Sample Portfolio Companies                          - Trulite\n- Arrow Tru-Line
Contact Name 1                Johnathon Borell \nManaging Director\n212 588 ...
Contact 2                                                                   NaN
Comments                      - DR knows Marc Leder ( I think)\n- They are b...
Name: 18, dtype: object)
(19, Priority                                                                    NaN
Company Name                                             Thomas H. Lee Partners
Website                                                             www.thl.com
AUM\n(Bns)                                                                 10.0
Sectors                                                     - Consumer & Retail
Sample Portfolio Companies                      - Give & Go Bakery\n- CTI Foods
Contact Name 1                Douglas A. Haber, Managing Director\n617-227-1050
Contact 2                                                                   NaN
Comments                      - Big in consumer and retail industry\n- Have ...
Name: 19, dtype: object)
(20, Priority                                                                    NaN
Company Name                                               TSG Cosumer Partners
Website                                                     www.tsgconsumer.com
AUM\n(Bns)                                                                  5.0
Sectors                                                       - Consumer Brands
Sample Portfolio Companies           - Smashbox\n- Beauty Bands\n- Elf\n- Cutex
Contact Name 1                Michael Layman, Managing Director\n415.217.231...
Contact 2                                                                   NaN
Comments                      - they are purely consumer focussed\n- Seems t...
Name: 20, dtype: object)

In [61]:
print(pe_firms.drop(["Priority"], axis = 1))

                 Company Name                     Website  AUM\n(Bns)  \
1            AEA Investors LP        www.aeainvestors.com        10.0
2        Audax Private Equity  www.audaxprivateequity.com        11.5
3                CCMP Capital         www.ccmpcapital.com        12.0
4     Clayton Dubilier & Rice             www.cdr-inc.com        18.0
5          Crestview Partners           www.crestview.com        20.0
6             Genstar Capital              www.gencap.com         8.5
7         Golden Gate Capital       www.goldengatecap.com        14.0
8                 Gores Group               www.gores.com         2.4
9            Harvest Partners     www.harvestpartners.com         2.0
10       Irving Place Capital  www.irvingplacecapital.com         4.4
11            Kelso & Company               www.kelso.com        11.2
12       Kohlberg and Company            www.kohlberg.com         7.5
13    KPS Capital Partners LP             www.kpsfund.com         5.2
14        Nautic Partners LLC              www.nautic.com        13.0
15  Palladium Equity Partners     www.palladiumequity.com         2.1
16            Platinum Equity      www.platinumequity.com         6.5
17      The Riverside Company    www.riversidecompany.com         6.0
18       Sun Capital Partners          www.suncappart.com         9.0
19     Thomas H. Lee Partners                 www.thl.com        10.0
20       TSG Cosumer Partners         www.tsgconsumer.com         5.0

                                              Sectors  \
1                   - Consumer products\n- Industrial
2                                        - Industrial
3                   - Consumer products\n- Industrial
4                   - Consumer products\n- Industrial
5                               - Industrial Products
6                               - Industrial Products
7                   - Consumer products\n- Industrial
8                   - Consumer products\n- Industrial
9                               - Industrial Products
10                  - Consumer products\n- Industrial
11           - Consumer Products\n- Building products
12                  - Industrial\n- Consumer Products
13                  - Consumer products\n- Industrial
14                              - Industrial Products
15                  - Consumer products\n- Industrial
16                              - Industrial Products
17  - Consumer Brands\n- Specialty Mfg and Distrib...
18                   - Consumer Brands\n- Industrials
19                                - Consumer & Retail
20                                  - Consumer Brands

                           Sample Portfolio Companies  \
1            - Traeger (Current)\n- Barnet (Cosmetic)
2                          - Chem Specialty Chemicals
3             - Jetro Cash & Carry\n- Shoes for Crews
4     - Roofing Supply Group\n- US Foods\n- HD Supply
5        - Key Safety Systems\n- Accuride corporation
6        - Pretium Packaging\n- Fort Dearborn Company
7                             - Eddie Bauer\n- Pacsun
8                      - Sage Automotive (previously)
9   - Associated Materials (Prior)\n- Driven Brand...
10        - Bendon\n- New York and Co\n- Rag and Bone
11                - Augusta Sportsware\n- Eagle Foods
12  - Nelson (Neutraceutical)\n- NBG Home Décor Pr...
13                             - Taylor Made\n- Winoa
14  - Custom Windows\n- Precision Engineered Products
15                     - Sahale Snacks\n- Kars Snacks
16  - SCM Metal Products\n- International textile ...
17                   - Lille Baby\n- Blue Electronics
18                        - Trulite\n- Arrow Tru-Line
19                    - Give & Go Bakery\n- CTI Foods
20         - Smashbox\n- Beauty Bands\n- Elf\n- Cutex

                                       Contact Name 1  \
1                        Martin Eltrich, III, Partner
2     Christopher Satti, Business Dev\n(857) 294-6640
3                                     Richard Zannino
4                                                 NaN
5                                  Alex Rose, Partner
6      Tony Salewski, Managing Director\n415 834 2350
7      Dave Thomas \nManaging Director\n415 983 2700
8                                                 NaN
9           Ira D. Kleinman, Senior Managing Director
10       David Knoch, Strategic Services and Partners
11  Alexander Lynn \nManaging Director\n212 751 39...
12                                                NaN
13                                                NaN
14  Bernard V. Buonanno\nbbuonanno@nautic.com\n(40...
15                                                NaN
16   David Boutry, Principal Bus Dev\n+1 212.905.0010
17  Jeremy Holland \nPrincipal of Origination Cons...
18  Johnathon Borell \nManaging Director\n212 588 ...
19  Douglas A. Haber, Managing Director\n617-227-1050
20  Michael Layman, Managing Director\n415.217.231...

                                            Contact 2  \
1                                                 NaN
2                                                 NaN
3                           Will Jaudes \nPrincipal
4                                                 NaN
5                                                 NaN
6                                                 NaN
7   Scott Middleman \nAssociate\n415 983 2700\nsmi...
8                                                 NaN
9   Paige Daly \nManaging Director\n212 599 6300 e...
10  Devraj Roy \nPartner, Industrials\n212 551 466...
11  Keith Castaldi \nVice President\n212 751 3939\...
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN

                                             Comments
1                                                 NaN
2   - We have experience with specialty chemicals ...
3                - Are big on Consumer and industrial
4                                                 NaN
5                    - Have industrial products focus
6                                                 NaN
7   Mr. Thomas focuses on investments in Industria...
8   - One of their strategies on some of their cas...
9   - Did addons for Associated Materials while th...
10  - Have both branded consumer companies and ind...
11  - DR says he knows Phil Berney or has heard of...
12                                                NaN
13                                                NaN
14  - We've had contact with them before for FS so...
15                                                NaN
16                                                NaN
17  - Have a full section of "seeking addons for ....
18  - DR knows Marc Leder ( I think)\n- They are b...
19  - Big in consumer and retail industry\n- Have ...
20  - they are purely consumer focussed\n- Seems t...

In [62]:
removed_priority = pe_firms.drop(["Priority"], axis = 1)
display(removed_priority)

,Company Name,Website,AUM\n(Bns),Sectors,Sample Portfolio Companies,Contact Name 1,Contact 2,Comments
1,AEA Investors LP,www.aeainvestors.com,10.0,- Consumer products\n- Industrial,- Traeger (Current)\n- Barnet (Cosmetic),"Martin Eltrich, III, Partner",NaN,NaN
2,Audax Private Equity,www.audaxprivateequity.com,11.5,- Industrial,- Chem Specialty Chemicals,"Christopher Satti, Business Dev\n(857) 294-6640",NaN,- We have experience with specialty chemicals ...
3,CCMP Capital,www.ccmpcapital.com,12.0,- Consumer products\n- Industrial,- Jetro Cash & Carry\n- Shoes for Crews,Richard Zannino,Will Jaudes \nPrincipal,- Are big on Consumer and industrial
4,Clayton Dubilier & Rice,www.cdr-inc.com,18.0,- Consumer products\n- Industrial,- Roofing Supply Group\n- US Foods\n- HD Supply,NaN,NaN,NaN
5,Crestview Partners,www.crestview.com,20.0,- Industrial Products,- Key Safety Systems\n- Accuride corporation,"Alex Rose, Partner",NaN,- Have industrial products focus
6,Genstar Capital,www.gencap.com,8.5,- Industrial Products,- Pretium Packaging\n- Fort Dearborn Company,"Tony Salewski, Managing Director\n415 834 2350",NaN,NaN
7,Golden Gate Capital,www.goldengatecap.com,14.0,- Consumer products\n- Industrial,- Eddie Bauer\n- Pacsun,Dave Thomas \nManaging Director\n415 983 2700,Scott Middleman \nAssociate\n415 983 2700\nsmi...,Mr. Thomas focuses on investments in Industria...
8,Gores Group,www.gores.com,2.4,- Consumer products\n- Industrial,- Sage Automotive (previously),NaN,NaN,- One of their strategies on some of their cas...
9,Harvest Partners,www.harvestpartners.com,2.0,- Industrial Products,- Associated Materials (Prior)\n- Driven Brand...,"Ira D. Kleinman, Senior Managing Director",Paige Daly \nManaging Director\n212 599 6300 e...,- Did addons for Associated Materials while th...
10,Irving Place Capital,www.irvingplacecapital.com,4.4,- Consumer products\n- Industrial,- Bendon\n- New York and Co\n- Rag and Bone,"David Knoch, Strategic Services and Partners","Devraj Roy \nPartner, Industrials\n212 551 466...",- Have both branded consumer companies and ind...
11,Kelso & Company,www.kelso.com,11.2,- Consumer Products\n- Building products,- Augusta Sportsware\n- Eagle Foods,Alexander Lynn \nManaging Director\n212 751 39...,Keith Castaldi \nVice President\n212 751 3939\...,- DR says he knows Phil Berney or has heard of...
12,Kohlberg and Company,www.kohlberg.com,7.5,- Industrial\n- Consumer Products,- Nelson (Neutraceutical)\n- NBG Home Décor Pr...,NaN,NaN,NaN
13,KPS Capital Partners LP,www.kpsfund.com,5.2,- Consumer products\n- Industrial,- Taylor Made\n- Winoa,NaN,NaN,NaN
14,Nautic Partners LLC,www.nautic.com,13.0,- Industrial Products,- Custom Windows\n- Precision Engineered Products,Bernard V. Buonanno\nbbuonanno@nautic.com\n(40...,NaN,- We've had contact with them before for FS so...
15,Palladium Equity Partners,www.palladiumequity.com,2.1,- Consumer products\n- Industrial,- Sahale Snacks\n- Kars Snacks,NaN,NaN,NaN
16,Platinum Equity,www.platinumequity.com,6.5,- Industrial Products,- SCM Metal Products\n- International textile ...,"David Boutry, Principal Bus Dev\n+1 212.905.0010",NaN,NaN
17,The Riverside Company,www.riversidecompany.com,6.0,- Consumer Brands\n- Specialty Mfg and Distrib...,- Lille Baby\n- Blue Electronics,Jeremy Holland \nPrincipal of Origination Cons...,NaN,"- Have a full section of ""seeking addons for ...."
18,Sun Capital Partners,www.suncappart.com,9.0,- Consumer Brands\n- Industrials,- Trulite\n- Arrow Tru-Line,Johnathon Borell \nManaging Director\n212 588 ...,NaN,- DR knows Marc Leder ( I think)\n- They are b...
19,Thomas H. Lee Partners,www.thl.com,10.0,- Consumer & Retail,- Give & Go Bakery\n- CTI Foods,"Douglas A. Haber, Managing Director\n617-227-1050",NaN,- Big in consumer and retail industry\n- Have ...
20,TSG Cosumer Partners,www.tsgconsumer.com,5.0,- Consumer Brands,- Smashbox\n- Beauty Bands\n- Elf\n- Cutex,"Michael Layman, Managing Director\n415.217.231...",NaN,- they are purely consumer focussed\n- Seems t...

In [ ]:
only_sting_col = removed_priority.drop(["AUM\n(Bns)"], axis = 1)
display(only_sting_col)

,Company Name,Website,Sectors,Sample Portfolio Companies,Contact Name 1,Contact 2,Comments
1,AEA Investors LP,www.aeainvestors.com,- Consumer products\n- Industrial,- Traeger (Current)\n- Barnet (Cosmetic),"Martin Eltrich, III, Partner",NaN,NaN
2,Audax Private Equity,www.audaxprivateequity.com,- Industrial,- Chem Specialty Chemicals,"Christopher Satti, Business Dev\n(857) 294-6640",NaN,- We have experience with specialty chemicals ...
3,CCMP Capital,www.ccmpcapital.com,- Consumer products\n- Industrial,- Jetro Cash & Carry\n- Shoes for Crews,Richard Zannino,Will Jaudes \nPrincipal,- Are big on Consumer and industrial
4,Clayton Dubilier & Rice,www.cdr-inc.com,- Consumer products\n- Industrial,- Roofing Supply Group\n- US Foods\n- HD Supply,NaN,NaN,NaN
5,Crestview Partners,www.crestview.com,- Industrial Products,- Key Safety Systems\n- Accuride corporation,"Alex Rose, Partner",NaN,- Have industrial products focus
6,Genstar Capital,www.gencap.com,- Industrial Products,- Pretium Packaging\n- Fort Dearborn Company,"Tony Salewski, Managing Director\n415 834 2350",NaN,NaN
7,Golden Gate Capital,www.goldengatecap.com,- Consumer products\n- Industrial,- Eddie Bauer\n- Pacsun,Dave Thomas \nManaging Director\n415 983 2700,Scott Middleman \nAssociate\n415 983 2700\nsmi...,Mr. Thomas focuses on investments in Industria...
8,Gores Group,www.gores.com,- Consumer products\n- Industrial,- Sage Automotive (previously),NaN,NaN,- One of their strategies on some of their cas...
9,Harvest Partners,www.harvestpartners.com,- Industrial Products,- Associated Materials (Prior)\n- Driven Brand...,"Ira D. Kleinman, Senior Managing Director",Paige Daly \nManaging Director\n212 599 6300 e...,- Did addons for Associated Materials while th...
10,Irving Place Capital,www.irvingplacecapital.com,- Consumer products\n- Industrial,- Bendon\n- New York and Co\n- Rag and Bone,"David Knoch, Strategic Services and Partners","Devraj Roy \nPartner, Industrials\n212 551 466...",- Have both branded consumer companies and ind...
11,Kelso & Company,www.kelso.com,- Consumer Products\n- Building products,- Augusta Sportsware\n- Eagle Foods,Alexander Lynn \nManaging Director\n212 751 39...,Keith Castaldi \nVice President\n212 751 3939\...,- DR says he knows Phil Berney or has heard of...
12,Kohlberg and Company,www.kohlberg.com,- Industrial\n- Consumer Products,- Nelson (Neutraceutical)\n- NBG Home Décor Pr...,NaN,NaN,NaN
13,KPS Capital Partners LP,www.kpsfund.com,- Consumer products\n- Industrial,- Taylor Made\n- Winoa,NaN,NaN,NaN
14,Nautic Partners LLC,www.nautic.com,- Industrial Products,- Custom Windows\n- Precision Engineered Products,Bernard V. Buonanno\nbbuonanno@nautic.com\n(40...,NaN,- We've had contact with them before for FS so...
15,Palladium Equity Partners,www.palladiumequity.com,- Consumer products\n- Industrial,- Sahale Snacks\n- Kars Snacks,NaN,NaN,NaN
16,Platinum Equity,www.platinumequity.com,- Industrial Products,- SCM Metal Products\n- International textile ...,"David Boutry, Principal Bus Dev\n+1 212.905.0010",NaN,NaN
17,The Riverside Company,www.riversidecompany.com,- Consumer Brands\n- Specialty Mfg and Distrib...,- Lille Baby\n- Blue Electronics,Jeremy Holland \nPrincipal of Origination Cons...,NaN,"- Have a full section of ""seeking addons for ...."
18,Sun Capital Partners,www.suncappart.com,- Consumer Brands\n- Industrials,- Trulite\n- Arrow Tru-Line,Johnathon Borell \nManaging Director\n212 588 ...,NaN,- DR knows Marc Leder ( I think)\n- They are b...
19,Thomas H. Lee Partners,www.thl.com,- Consumer & Retail,- Give & Go Bakery\n- CTI Foods,"Douglas A. Haber, Managing Director\n617-227-1050",NaN,- Big in consumer and retail industry\n- Have ...
20,TSG Cosumer Partners,www.tsgconsumer.com,- Consumer Brands,- Smashbox\n- Beauty Bands\n- Elf\n- Cutex,"Michael Layman, Managing Director\n415.217.231...",NaN,- they are purely consumer focussed\n- Seems t...

In [67]:
only_sting_col.describe()

,Company Name,Website,Sectors,Sample Portfolio Companies,Contact Name 1,Contact 2,Comments
count,20,20,20,20,15,5,13
unique,20,20,9,20,15,5,13
top,AEA Investors LP,www.aeainvestors.com,- Consumer products\n- Industrial,- Traeger (Current)\n- Barnet (Cosmetic),"Martin Eltrich, III, Partner",Will Jaudes \nPrincipal,- We have experience with specialty chemicals ...
freq,1,1,8,1,1,1,1